//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ActionsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActionsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Engine.Resources.ActionsResource", typeof(ActionsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} to fire.
        /// </summary>
        internal static string AddToFire {
            get {
                return ResourceManager.GetString("AddToFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build grass bed.
        /// </summary>
        internal static string BuildGrassBed {
            get {
                return ResourceManager.GetString("BuildGrassBed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect {0}.
        /// </summary>
        internal static string Collect {
            get {
                return ResourceManager.GetString("Collect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Digging stick.
        /// </summary>
        internal static string CreateDiggingStick {
            get {
                return ResourceManager.GetString("CreateDiggingStick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Sharp stone.
        /// </summary>
        internal static string CreateSharpStone {
            get {
                return ResourceManager.GetString("CreateSharpStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Stone axe.
        /// </summary>
        internal static string CreateStoneAxe {
            get {
                return ResourceManager.GetString("CreateStoneAxe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Fire.
        /// </summary>
        internal static string MakeFire {
            get {
                return ResourceManager.GetString("MakeFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick.
        /// </summary>
        internal static string Pick {
            get {
                return ResourceManager.GetString("Pick", resourceCulture);
            }
        }
    }
}
