//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Engine.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resource {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Engine.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple.
        /// </summary>
        internal static string Apple {
            get {
                return ResourceManager.GetString("Apple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burovik.
        /// </summary>
        internal static string Burovik {
            get {
                return ResourceManager.GetString("Burovik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bush.
        /// </summary>
        internal static string Bush {
            get {
                return ResourceManager.GetString("Bush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cone.
        /// </summary>
        internal static string Cone {
            get {
                return ResourceManager.GetString("Cone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digging stick.
        /// </summary>
        internal static string DiggingStick {
            get {
                return ResourceManager.GetString("DiggingStick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant.
        /// </summary>
        internal static string Plant {
            get {
                return ResourceManager.GetString("Plant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roasted apple.
        /// </summary>
        internal static string RoastedApple {
            get {
                return ResourceManager.GetString("RoastedApple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roasted burovik.
        /// </summary>
        internal static string RoastedBurovik {
            get {
                return ResourceManager.GetString("RoastedBurovik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock.
        /// </summary>
        internal static string Rock {
            get {
                return ResourceManager.GetString("Rock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        internal static string Root {
            get {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharp stone.
        /// </summary>
        internal static string SharpStone {
            get {
                return ResourceManager.GetString("SharpStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone Axe.
        /// </summary>
        internal static string StoneAxe {
            get {
                return ResourceManager.GetString("StoneAxe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twig.
        /// </summary>
        internal static string Twig {
            get {
                return ResourceManager.GetString("Twig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wickiup.
        /// </summary>
        internal static string Wickiup {
            get {
                return ResourceManager.GetString("Wickiup", resourceCulture);
            }
        }
    }
}
